### PR TITLE
Add Get Diagnostics service for chargers that support it

### PR DESCRIPTION
**Pull request by drc38**

### CODE REVIEW

**Review by lbbrhzn — COMMENTED** [review]
Looks like there are a lot of changes, not just for diagnostics. Is that because you've merged on other PRs?

**Comment by drc38** [comment]
It includes #106, so assume once #106 is merged then the get diagnostics code will be left. Is there any way to link it to #106 so it shows diffs from there?

**Review by lbbrhzn — APPROVED** [review]

**Comment by lbbrhzn** [comment]
There are some merge conflicts that need to be resolved before this can be merged.

**Comment by drc38** [comment]
> There are some merge conflicts that need to be resolved before this can be merged.

Cheers, conflicts resolved so it can be merged now.

**Pull request merged**
