### PR TITLE
ocpp: add update firmware function

### PR DESCRIPTION
**Pull request by drc38**
Hi @lbbrhzn, this function can be used for a custom service call when ready as referred to in #34

### CODE REVIEW

**Comment by jeremycoppey** [comment]
Ok guys,
Good news, my charger just (month old) got a firmware update released.
So I can test this feature from the moment you merge this into main.
You are talking about the firmware_url any idea where I can locate this?
The charger product page has a link to a firmware page: https://www.se.com/ww/en/download/document/MFR4341700/
But behind the download button is a zip file containing the file with the firmware.
If I read your code you need the update file directly.
Or should I ask Schneider for a public url where the file is hosted?

**Comment by drc38** [comment]
> Ok guys,
> Good news, my charger just (month old) got a firmware update released.
> So I can test this feature from the moment you merge this into main.
> You are talking about the firmware_url any idea where I can locate this?
> The charger product page has a link to a firmware page: https://www.se.com/ww/en/download/document/MFR4341700/
> But behind the download button is a zip file containing the file with the firmware.
> If I read your code you need the update file directly.
> Or should I ask Schneider for a public url where the file is hosted?

Hi Jeremy, there's still a bit or work required before this function can be used in HA as a custom service. So it won't be available after the merge. Your charger may accept the zip file directly, otherwise you could unzip and load to onedrive or similar cloud server. The metric "FW.Status" can be used to monitor the update process. I take it your charger supports the Firmware Management profile?

**Comment by jeremycoppey** [comment]
Yes my charger supports the following: 
Core, FirmwareManagement, Reservation, SmartCharging

I will do a manual update then.
Looks like it adds some extra features:
image

Do you know what they mean with this feature? (see page 7 of the release notes)
[EVlink_charging station_Release_Note_R07_run17.pdf](https://github.com/lbbrhzn/ocpp/files/6769349/EVlink_charging.station_Release_Note_R07_run17.pdf)

**Comment by drc38** [comment]
Clock aligned values are for accurately reporting energy used in given time periods eg 30min or 1hr required by Energy Retailers / Billing solutions. Not really of use for most personal applications.

**Comment by jeremycoppey** [comment]
sorry I just updated. 
But as they release frequently I don't think I will be waiting long for a new firmware update.

Thanks for the clarification.

**Comment by lbbrhzn** [comment]
hi @drc38, these changes look ok, thanks! I cannot download new firmware for my Wallbox charger myself, so I was not able to fully test it. 

Just a minor point: the pre-commit check for the formatting is failing. Did you run a pre-commit check before you pushed your changes? Just use `pip install pre-commit` to install

**Comment by drc38** [comment]
@lbbrhzn, thanks I wasn't sure whether the pre-commit process was supposed to do the reformatting or whether I needed to do it locally.

**Comment by lbbrhzn** [comment]
> @lbbrhzn, thanks I wasn't sure whether the pre-commit process was supposed to do the reformatting or whether I needed to do it locally.

You need to do it locally. The pre-commit actions are also done as an action on GitHub, and it will result in failed checks if there are still some formatting issues remaining.

**Pull request merged**
