### PR TITLE
101 improve phase processing

### PR DESCRIPTION
**Pull request by lbbrhzn**
See #101

### CODE REVIEW

**Comment by lbbrhzn** [comment]
Can you take a look if these changes work? I have not yet been able to fully test them...

**Comment by drc38** [comment]
Looking at the Tests error log it is saying there's an attribute error in your code when calling:
`Measurand.active_power_import.value`

**Comment by drc38** [comment]
> Looking at the Tests error log it is saying there's an attribute error in your code when calling:
> `Measurand.active_power_import.value`

Should be: `power_active_import`

**Comment by lbbrhzn** [comment]
Ok to merge?

**Pull request merged**
