### PR TITLE
Refactor Numbers for 2021.12+

### PR DESCRIPTION
**Pull request by drc38**

### CODE REVIEW

**Comment by lbbrhzn** [comment]
Is this number version persistent over restarts of home assistant?

**Comment by drc38** [comment]
> Is this number version persistent over restarts of home assistant?

Worth testing it, I'm not sure

**Comment by drc38** [comment]
Added in RestoreEntity to make it persistent over restarts

**Comment by lbbrhzn** [comment]
do you also resend the max current value when the charger reconnects?

**Comment by drc38** [comment]
> do you also resend the max current value when the charger reconnects?

No it doesn't, it shouldn't be necessary and could cause problems if the websocket connection is not stable.

**Review by lbbrhzn — APPROVED** [review]

**Pull request merged**
