### PR TITLE
bump python version in devcontainer to 3.12

### PR DESCRIPTION
**Pull request by scruysberghs**
bump pytest-homeassistant-custom-component to 0.13.148

### CODE REVIEW

**Review by scruysberghs — COMMENTED** [review]
try to fix incompatibility between python 3.11 and  pytest-homeassistant-custom-component==0.13.136

**Comment by lbbrhzn** [comment]
Tests are failing...

I suggest to split the python upgrade and the pytest-homeassistant upgrade to see which upgrade is causing the issues.

**Comment by drc38** [comment]
Also see suggested change to setup in https://github.com/lbbrhzn/ocpp/pull/1242#issuecomment-2224215064

**Comment by scruysberghs** [comment]
That change indeed helped with the python 3.12 and
pytest-homeassistant-custom-component==0.13.144 combo. I have the dev
environment running now from this fork :
https://github.com/scruysberghs/ocpp-1
Also added a forward for port 9000 to the devcontainer so I can finally
start playing with the ocpp stuff for my multi socket charging station.
I will also make an attempt to have the integration support multiple
charging stations. I have a use case for that where I want to use home
assistant as an energy management system to control 12 charging stations on
a company parking lot. Initial plan was to use evcc.io + HA integration and
set up all the charging stations there, but I want to learn more about OCPP
...

evcc.io has support for multiple sockets charging station and multiple
charging stations already,
https://docs.evcc.io/en/docs/devices/chargers#ocpp-16j-compatible-charger-with-smart-charging-profile

Regards
Steven

Op zo 4 aug 2024 om 21:04 schreef drc38 ***@***.***>:

**Review by lbbrhzn — APPROVED** [review]

**Pull request merged**
