### PR TITLE
ocpp: extend HA integration

### PR DESCRIPTION
**Pull request by drc38**
Hi, I have forked your repo and added some additional functionality and checks to prevent errors eg TriggerMessage is only sent if supported. However I am stuck at trying to add services to HA, eg to start and stop the charger. Do you have any experience with this, as I'd appreciate some help.

### CODE REVIEW

**Comment by drc38** [comment]
Note this is still work in progress and needs documentation updating etc

**Comment by lbbrhzn** [comment]
great, i'll take a look at your pull request, and test it on my Wallbox. In my experience every charger supports its own subset of OCPP. I have no experence with HA services, but i'll try my best!

**Comment by drc38** [comment]
The new `Features` metric contains which features the charger supports in addition to Core eg FirmwareManagement, SmartCharging. If we can figure out how to successfully register services then functionality such as updating firmware, applying charging profiles, stop charging can be incorporated into automations.

**Comment by jeremycoppey** [comment]
Happy to help test it.
@drc38 I logged some issues on the main repo. Can you check them out please?
Maybe the last one #8  is even fixed by your HA integration code.

**Comment by lbbrhzn** [comment]
> Hi, I have forked your repo and added some additional functionality and checks to prevent errors eg TriggerMessage is only sent if supported. However I am stuck at trying to add services to HA, eg to start and stop the charger. Do you have any experience with this, as I'd appreciate some help.

Would it make sense to use a simple switch to enable / stop the charging? A switch provides the API for service calls by default.

**Comment by drc38** [comment]
> Happy to help test it.
> @drc38 I logged some issues on the main repo. Can you check them out please?
> Maybe the last one #8 is even fixed by your HA integration code.

Yes this is, you can specify a unique name for the chargepoint in the yaml or it defaults to `ocpp`

**Comment by drc38** [comment]
> > Hi, I have forked your repo and added some additional functionality and checks to prevent errors eg TriggerMessage is only sent if supported. However I am stuck at trying to add services to HA, eg to start and stop the charger. Do you have any experience with this, as I'd appreciate some help.
> 
> Would it make sense to use a simple switch to enable / stop the charging? A switch provides the API for service calls by default.

A switch would make sense for start/stop charge,  and availability. Custom calls will still be needed for charge profile, firmware upload etc

**Comment by jeremycoppey** [comment]
> > Happy to help test it.
> > @drc38 I logged some issues on the main repo. Can you check them out please?
> > Maybe the last one #8 is even fixed by your HA integration code.
> 
> Yes this is, you can specify a unique name for the chargepoint in the yaml or it defaults to `ocpp`

Thanks,
Also tested the new release: works fine.
I still miss some info. only 3 properties return something:
Error.Code
Heartbeat
Status
image

**Comment by drc38** [comment]
> > > Happy to help test it.
> > > @drc38 I logged some issues on the main repo. Can you check them out please?
> > > Maybe the last one #8 is even fixed by your HA integration code.
> > 
> > 
> > Yes this is, you can specify a unique name for the chargepoint in the yaml or it defaults to `ocpp`
> 
> Thanks,
> Also tested the new release: works fine.
> I still miss some info. only 3 properties return something:
> Error.Code
> Heartbeat
> Status
> image

Seems odd that only some metrics are coming through. Suggest looking at the HA log for the messages sent from the charger to HA. Eg on connection get_configuration is called for SupportedFeatures which the charger is required to return eg Core as a minimum.

**Comment by jeremycoppey** [comment]
I have the following error:
`This error originated from a custom integration.

Logger: ocpp
Source: custom_components/ocpp/sensor.py:406
Integration: ocpp (documentation, issues)
First occurred: 1:00:25 PM (1 occurrences)
Last logged: 1:00:25 PM

Error while handling request '<Call - unique_id=4049, action=MeterValues, payload={'connectorId': 1, 'meterValue': [{'sampledValue': [{'value': '1582'}], 'timestamp': '2021-05-02T04:54:22Z'}], 'transactionId': 1234}>'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ocpp/charge_point.py", line 185, in _handle_call
    response = handler(**snake_case_payload)
  File "/usr/local/lib/python3.8/site-packages/ocpp/routing.py", line 33, in inner
    return func(*args, **kwargs)
  File "/config/custom_components/ocpp/sensor.py", line 406, in on_meter_values
    self._metrics[sampled_value["measurand"]] = sampled_value["value"]
KeyError: 'measurand'
`

**Comment by drc38** [comment]
Are you using a real charger? The meterValue payload above does not appear to conform to the 1.6j format.

**Comment by jeremycoppey** [comment]
Yes it is a real charger.
My OCPP config on the charger:
# Ocpp Conf

[OCPP]
ocppVersion=              1.6
ocppCentralAddress=       ws://192.168.1.21:9000
ocppBoxLocalPort=         8080
ocppBoxPublicIp=          
ocppBoxPublicPort=        8080
ocppBoxLocalSSL=          0
ocppBoxAddressReplyTo=    http://www.w3.org/2005/08/addressing/anonymous
ocppModemIpAddress=       192.168.0.254
ocppModemPresence=       0
modemType=                
confModemRetryInterval=   30
boxIdentity=              UNDEFINED
defaultIdTag=             UNDEFINED
isMeterValueSimulated=    false
MeterValuesAlignedData=   Energy.Active.Import.Register
MeterValuesSampledData=   Energy.Active.Import.Register
meterValueSampleInterval= 900
clockAlignedDataInterval= 0
ocppConnectTimeOut=       60
WebSocketPingInterval=    120
MinimumStatusDuration=    0
TransactionMessageRetryInterval=60
TransactionMessageAttempts=500
truncateBootNotificationsSerialNumbers=    true
serverCertificatePassword=UNDEFINED
clientHttpsOptions=       DEFAULT
cacheListEnabled=         false
enablePlugNumbering=      false
enableDoubleNotification=      false
lastAcceptedOcppCentralAddress=ws://192.168.1.21:9000/00:80:F4:43:0B:34
lastAcceptedBoxIdentity=       00:80:F4:43:0B:34
lastAcceptedHeartBeatInterval= 10
compressDiagnostic=            1
ocppEMDegradedModeEnabled=     0
EnergyLimitValue=       0
isEnergyLimitedActive=     false

**Comment by drc38** [comment]
Try the latest code see PR#8 as the transactionId should no longer be "1234" but rather the epoch time. If you still have a problem send through the HA log before and after the error.

**Comment by jeremycoppey** [comment]
Ok I have updated it. it's version #11 
I see already some more data (unplugged)
Feature and ID is filled.
I will update you guys when I plug the car back in,

**Pull request merged**
