### PR TITLE
Add extra states to Charge Control switch

### PR DESCRIPTION
**Pull request by drc38**

### CODE REVIEW

**Comment by drc38** [comment]
@lbbrhzn no checks are running on this?

**Comment by lbbrhzn** [comment]
Looks like something is broken in the GitHub workflows.

**Comment by drc38** [comment]
> Looks like something is broken in the GitHub workflows.

Can you run workflows manually on this PR?

**Comment by lbbrhzn** [comment]
No, I cannot. They are working for other pull requests though.
Can you copy your changes to a different branch and resubmit your pull request?

**Comment by drc38** [comment]
> No, I cannot. They are working for other pull requests though. Can you copy your changes to a different branch and resubmit your pull request?

Looks like it sorted itself with the 2nd commit.

**Comment by lbbrhzn** [comment]
looks good to me!

**Pull request merged**
