### PR TITLE
default to Core profile for malformed responses

### PR DESCRIPTION
**Pull request by drc38**

### CODE REVIEW

**Comment by lbbrhzn** [comment]
looks good. Should we log a warning when an unknown FeatureProfile is received?
Should be possible using elifs.

**Comment by lbbrhzn** [comment]
Add a test with an empty featureprofile?

**Comment by drc38** [comment]
> Add a test with an empty featureprofile?

I've added a test in for that but I haven't figured out why it doesn't run yet.

**Comment by drc38** [comment]
Should be good to merge now

**Pull request merged**
