### PR TITLE
Add "force smart charging" option to configuration flow

### PR DESCRIPTION
**Pull request by birneee**
Add "force smart charging" option to configuration flow
Suggested by [drc38](https://github.com/drc38) in https://github.com/lbbrhzn/ocpp/pull/599#issuecomment-1225090294, https://github.com/lbbrhzn/ocpp/discussions/474#discussioncomment-2577256
Fixes https://github.com/lbbrhzn/ocpp/issues/510, https://github.com/lbbrhzn/ocpp/pull/599 (at least partially)
Fixes https://github.com/lbbrhzn/ocpp/discussions/474

### CODE REVIEW

**Comment by drc38** [comment]
Please update the tests to include the new config option and fix linting, cheers

**Review by drc38 — COMMENTED** [review]
Best to add your test in this section `# test ocpp rejection messages sent from charger to cms`
The dummy charger will return a blank response to the get FeatureProfiles configuration and it can be asserted the cms returns SmartCharging when the config flow option is set to True

**Comment by sreichholf** [comment]
I do have a suggestion for this (I do own a ABB Terra AC so I am actually affected by this)

Wouldn't cases like these be a typical scenario for "vendor/model specific quirks" as uses e.g. in ZHA?
Most typical users barely understand options like this and start a "trial and error session" until everything does what they want it to.

At least for known cases it should be possible to detect device specific quirks and handle them within the code and in return improve the "plug 'n play" experience for users.

**Comment by drc38** [comment]
> I do have a suggestion for issues like this (I do own a ABB Terra AC so I am actually affected by this).
> 
> Wouldn't cases like this one be a typical scenario for "vendor/model specific quirks" as used e.g. in ZHA? Most typical users barely understand options like this and start a "trial and error session" until everything does what they want it to. Plus there is a real "threat" that the list of "device specific options" gets longer and longer.
> 
> At least for known cases it should be possible to detect device specific quirks and handle them within the code and in return improve the "plug 'n play" experience for users.

In terms of the Ocpp HA integration it was intended to be completely generic to the standard and not to really accommodate device specific quirks. However over time it has become clear a number of manufacturers are not fully compliant with the standard or there are some "grey" areas eg websockets, supporting a feature but not reporting that it does. 

To assist others with device specific quirks or configuration this can be documented in the docs via a PR or the repo forked to create a device/manufacturer specific integration. Hopefully over time most quirks will be addressed through firmware upgrades.

**Comment by sreichholf** [comment]
I don't mean to be to pessimitic, but having worked with communication "standards" in multiple industries (primarily EDI in the automotive sector Automotive and pretty much every single standard ever used in the "Enterntainment Sector" (DVB, HDMI, CeC) this seems like an unachievable goal.

I do understand and honor the concept/wish though and agree that user-side configuration is fine when documented properly.

**Pull request merged**
