### PR TITLE
add config option to skip schema validation

### PR DESCRIPTION
**Pull request by lbbrhzn**

### CODE REVIEW

**Review by drc38 — APPROVED** [review]
Lgtm

**Comment by N3rdix** [comment]
Couldn’t find any info what this parameter does, will this be added to the docs?
At least it sounds interesting from my perspective 😁

**Comment by lbbrhzn** [comment]
Hi @N3rdix, the ocpp package we use verifies that the communication adheres to the schema defined in the standard.
In case there is a deviation it throws an exception and the connection is dropped. This configuration option allows the user to disable the validation.

**Comment by N3rdix** [comment]
Hey @lbbrhzn,
thanks for the explanation und great work by the way!

**Pull request merged**
