### PR TITLE
Avoid spurious reconnects

### PR DESCRIPTION
**Pull request by drc38**
Adds a counter to avoid forcing a reconnect if the connection is back online by the next 2 tries

### CODE REVIEW

**Review by lbbrhzn — CHANGES_REQUESTED** [review]
Please make the timeout_counter configurable. This will also aid in testing.
Can you add tests for this functionality?

**Comment by drc38** [comment]
I've added the basic tests, I'm unsure how to go about replacing the websockets pong response in a fixture to cause it to raise the timeout exception though

**Comment by lbbrhzn** [comment]
I thing you can disable the websocket connection by manually setting state to CLOSING.
This will prevent pongs being sent.

**Review by lbbrhzn — CHANGES_REQUESTED** [review]
WEBSOCKET_CLOSE_TRIES is confusing. 
I would prefer WEBSOCKET_PING_TRIES.

**Review by lbbrhzn — APPROVED** [review]
great!

**Pull request merged**
