### PR TITLE
ocpp: add websocket subprotocol support check

### PR DESCRIPTION
**Pull request by drc38**

### CODE REVIEW

**Review by lbbrhzn — APPROVED** [review]
Which subprotocols do we support?

**Comment by drc38** [comment]
Only ocpp1.6

**Comment by lbbrhzn** [comment]
Just wondering why this is needed. Doesn't websockets already check for the correct subprotocol by itself?

**Comment by drc38** [comment]
I don't think so based on the comment in the example code here: https://github.com/mobilityhouse/ocpp/blob/master/examples/v16/central_system.py

**Pull request merged**
