### PR TITLE
Revert "build(deps): bump sqlalchemy from 1.4.17 to 1.4.21 in /.github/workflows"

### PR DESCRIPTION
**Pull request by drc38**
Reverts lbbrhzn/ocpp#74

### CODE REVIEW

**Comment by lbbrhzn** [comment]
Why do we require that specific sqlachemy version?

**Comment by drc38** [comment]
`pytest-homeassistant-custom-component 0.4.2 depends on sqlalchemy==1.4.17`

**Comment by lbbrhzn** [comment]
Is it possible to remove the requirement from requirements-dev.txt, and let pip auto detect this?

If not, we should add a comment to our requirements-dev.txt:

`# pytest-homeassistant-custom-component 0.4.2 depends on
sqlalchemy==1.4.17`

**Comment by drc38** [comment]
Give it a go and see, I'm not familiar with how pip determines requirements

**Pull request merged**
