### PR TITLE
temp fix for jsonschema

### PR DESCRIPTION
**Pull request by drc38**

### CODE REVIEW

**Review by lbbrhzn — COMMENTED** [review]
Pinning the jsonschema to a particular version may easily create conflicts with other integrations. Is there any other way to fix this?

**Comment by lbbrhzn** [comment]
The tests are failing with the change. Any idea why?

**Comment by lbbrhzn** [comment]
Approving even with failed tests to work around a problem in upstream package.

**Comment by drc38** [comment]
> The tests are failing with the change. Any idea why?

No idea, suggest updating to python 3.11, HA and pytest to latest. Then try and solve any issues from there.

**Pull request merged**
