### PR TITLE
Close old connection before switching to new

### PR DESCRIPTION
**Pull request by lbbrhzn**
Upon reconnect, make sure the old connection is closed before we start using the new connection

### CODE REVIEW

**Review by drc38 — APPROVED** [review]

**Comment by lbbrhzn** [comment]
@drc38, It looks like we no longer trigger a boot notification, is this not needed?
Or am I overlooking something... it seems to have test coverage.

**Comment by drc38** [comment]
> @drc38, It looks like we no longer trigger a boot notification, is this not needed? Or am I overlooking something... it seems to have test coverage.

Not all chargers support it, I can't see that it is needed but it could be added back in.

**Comment by lbbrhzn** [comment]
The boot notification contains useful device information, such as vendor, serial, firmware version. Without trigger it will only be sent after a reboot.  

Here's a scenario where I would like to trigger a boot notification: I tend to disable ocpp for firmware upgrades of my charger, which are done through the original management platform, and re-enable ocpp after the update. In this case the ocpp integration does not see a boot notification, so the firmware version is not updated. I propose to trigger the boot notification in post_connect if the Smart Charging profile is supported. Note that this should not trigger an actual reboot of the charger, just a resend of the information!

**Comment by drc38** [comment]
Use the Remote profile, as that indicates support for trigger notifications rather than smart charging.

**Comment by lbbrhzn** [comment]
Ah, you're right. The standard lists it incorrectly in the table, but the erratum fixes this.

**Comment by drc38** [comment]
@lbbrhzn on 0.4.11 I get the ping latency metric but no pong metric? Is it the same for you?

**Comment by lbbrhzn** [comment]
yes, i made a copy paste error in enums.py. will be fixed!

**Comment by drc38** [comment]
That explains why it is also still reporting a similar latency time...it had me confused 🙃

**Pull request merged**
