### PR TITLE
revised PR

### PR DESCRIPTION
**Pull request by drc38**
@lbbrhzn, note I had to update how charge points were referenced to `self.cpid` otherwise if in the config flow you set a cpid that is different to the `cp_id` reported by the charger the metrics will not report.

### CODE REVIEW

**Comment by lbbrhzn** [comment]
Hi @drc38, I have noticed this also, and have been working on automatic creation of the device and the related entitties upon connect.

**Comment by drc38** [comment]
> Hi @drc38, I have noticed this also, and have been working on automatic creation of the device and the related entitties upon connect.

Hi @lbbrhzn, hopefully these changes are straight forward to include in your updated entity creation flow.

**Review by lbbrhzn — APPROVED** [review]

**Comment by jeremycoppey** [comment]
Hey Guys,
Fantastic job,

I was away for a couple weeks and came back to this integration to see a great progress.
I installed and setup the new integration like a charm. 
Would be nice to adapt the Readme file in the future. (maybe i will do it, so you can concentrate on the important stuff) 
Maybe it would be nice to clarify the new switches functionality and how to add the integration to HASS.

Kind regards

**Comment by lbbrhzn** [comment]
Thanks Jeremy.. you're welcome to help out with the documentation!

**Pull request merged**
