### PR TITLE
Update api.py

### PR DESCRIPTION
**Pull request by lbbrhzn**
Bugfix processing phase measurands. See #95

### CODE REVIEW

**Comment by lbbrhzn** [comment]
@drc38, why are positive voltages treated differently from negative?

```Python

           if metric in Measurand.voltage.value:
                sum = (
                    value[Phase.l1_n.value]
                    + value[Phase.l2_n.value]
                    + value[Phase.l3_n.value]
                )
                if sum > 0:
                    self._metrics[metric] = round(sum / 3, 1)
                else:
                    self._metrics[metric] = round(sum, 1)
```

**Comment by drc38** [comment]
> @drc38, why are positive voltages treated differently from negative?
> 
> ```python
>            if metric in Measurand.voltage.value:
>                 sum = (
>                     value[Phase.l1_n.value]
>                     + value[Phase.l2_n.value]
>                     + value[Phase.l3_n.value]
>                 )
>                 if sum > 0:
>                     self._metrics[metric] = round(sum / 3, 1)
>                 else:
>                     self._metrics[metric] = round(sum, 1)
> ```

There should not be negative voltages, and the >0 was to protect against a div by 0 error.

**Review by drc38 — APPROVED** [review]

**Comment by lbbrhzn** [comment]
> ```python
>   if sum > 0:
>                     self._metrics[metric] = round(sum / 3, 1)
>                 else:
>                     self._metrics[metric] = round(sum, 1)
> ```

You’re never dividing by sum though. And if sum equals zero, the metric value will be zero.

Ok if I just change it to:

```python
self._metrics[metric] = round(sum / 3, 1)
```

**Comment by drc38** [comment]
😄 good spotting, I was working too late. Please update

**Comment by drc38** [comment]
Will you also update prior loop to reference `self._extra_attr`?

**Comment by lbbrhzn** [comment]
> Will you also update prior loop to reference `self._extra_attr`?

I will keep that the same for now. I do think there is some room for simplification. We just want to average the voltages, and sum the currents, right?

**Pull request merged**
