### PR TITLE
Fix bug in transactionId match

### PR DESCRIPTION
**Pull request by drc38**

### CODE REVIEW

**Comment by drc38** [comment]
@lbbrhzn any ideas why in testing of the `send_start_transaction` the charge point's `active_transactionId` is not being updated to the Id provided by the cms server and instead reporting 1000 which is set at init?

**Review by lbbrhzn — APPROVED** [review]

**Review by lbbrhzn — APPROVED** [review]

**Comment by lbbrhzn** [comment]
looks good to me, but tests are not passing yet !

**Comment by drc38** [comment]
@lbbrhzn, should be good to merge now. Some extra tests can now be added eg function to send clock meter data

**Comment by lbbrhzn** [comment]
Looking good, nice test coverage! 
Ok to merge now?

**Pull request merged**
